### ISSUE TITLE
Questions about mod

### ISSUE THREAD

**Issue by Penguinplus123** [ItsKirby69/MineDusty#1]
Is this like old minecraft tech mods?
Are you still planning on working on this?
Are there any public releases?
I dont have discord so this is the only way i can ask these questions

**Comment by ItsKirby69** [comment]
I should've closed the repo temporarily as I don't have the time to work on the mod. I still have some plans on releases though. So far, the working idea is to have this mod as a decoration adding mod, mostly for environmental things. I hope this clears up anything. I'll update the repo with some new changes soon.
