### ISSUE TITLE
Я не могу скачать мод

### ISSUE THREAD

**Issue by RSBLITSI** [ItsKirby69/MineDusty#2]
Я не могу скачать этот мод выдаёт ошибку соединения хотя соединение есть и другие моды скачивает спокойно
![Screenshot_20240731-040357](https://github.com/user-attachments/assets/8fc0b8f8-bf57-4548-b6da-c124abdfde56)

**Comment by ItsKirby69** [comment]
Sorry for the late response! You should be able to download the mod if you view releases and Install the latest version.

**Comment by ItsKirby69** [comment]
This issue should now be fixed
